2013-10-19 11:47:58,404 - WARNING: 404 GET /vincentpc.github.com (162.105.247.19) 1.52ms
2013-10-19 11:47:58,929 - WARNING: 404 GET /favicon.ico (162.105.247.19) 0.46ms
2013-10-19 11:48:05,923 - WARNING: 404 GET /vincentpc.github.com (162.105.247.19) 0.55ms
2013-10-19 12:06:27,081 - WARNING: 404 GET /vincentpc.github.com (119.147.146.118) 0.75ms
2013-10-19 12:06:31,298 - WARNING: 404 GET /vincentpc.github.com (119.147.146.118) 0.59ms
2013-10-19 12:11:24,377 - WARNING: 404 GET /vincentpc.github.com (162.105.247.19) 0.55ms
2013-10-19 12:17:58,167 - WARNING: 404 GET /vincentpc.github.com (101.226.66.178) 0.57ms
2013-10-19 12:17:58,716 - WARNING: 404 GET /vincentpc.github.com (180.153.211.190) 0.56ms
2013-10-19 16:54:48,444 - WARNING: 405 HEAD / (177.200.70.149) 0.64ms
2013-10-19 18:50:52,742 - WARNING: 404 GET http://www.baidu.com/ (95.28.219.120) 0.84ms
2013-10-19 21:36:20,124 - WARNING: 404 GET http://www.baidu.com/ (218.22.71.130) 0.55ms
2013-10-19 23:26:54,180 - WARNING: 404 GET http://www.baidu.com/ (222.89.55.123) 0.53ms
2013-10-20 00:20:31,374 - WARNING: 405 HEAD / (177.200.70.161) 0.50ms
2013-10-20 01:10:04,918 - ERROR: Uncaught exception POST /yixinpublic?timestamp=1382231397&nonce=8187909658301471&signature=a03794ab02183662611410c4825d4a6cd7e4e69a (223.252.198.65)
HTTPRequest(protocol='http', host='54.200.177.39', method='POST', uri='/yixinpublic?timestamp=1382231397&nonce=8187909658301471&signature=a03794ab02183662611410c4825d4a6cd7e4e69a', version='HTTP/1.1', remote_ip='223.252.198.65', headers={'Content-Length': '302', 'Host': '54.200.177.39', 'Content-Encoding': 'UTF-8', 'Content-Type': 'text/xml; charset=UTF-8', 'Connection': 'Keep-Alive', 'Accept': 'application/xml', 'User-Agent': 'Netease/0.1'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1141, in _when_complete
    callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1162, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "app.py", line 27, in post
    data = processXml(self.request.body)
  File "/home/ubuntu/tornado/wechatwiki/handlers/processxml.py", line 95, in processXml
    return response
UnboundLocalError: local variable 'response' referenced before assignment
2013-10-20 01:10:04,930 - ERROR: 500 POST /yixinpublic?timestamp=1382231397&nonce=8187909658301471&signature=a03794ab02183662611410c4825d4a6cd7e4e69a (223.252.198.65) 12.84ms
2013-10-20 01:10:28,308 - ERROR: Uncaught exception POST /yixinpublic?timestamp=1382231421&nonce=8187933050564107&signature=d74ff5c052de356fca7ed872eb64d69dcacbe5a4 (223.252.198.65)
HTTPRequest(protocol='http', host='54.200.177.39', method='POST', uri='/yixinpublic?timestamp=1382231421&nonce=8187933050564107&signature=d74ff5c052de356fca7ed872eb64d69dcacbe5a4', version='HTTP/1.1', remote_ip='223.252.198.65', headers={'Content-Length': '300', 'Host': '54.200.177.39', 'Content-Encoding': 'UTF-8', 'Content-Type': 'text/xml; charset=UTF-8', 'Connection': 'Keep-Alive', 'Accept': 'application/xml', 'User-Agent': 'Netease/0.1'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1141, in _when_complete
    callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1162, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "app.py", line 27, in post
    data = processXml(self.request.body)
  File "/home/ubuntu/tornado/wechatwiki/handlers/processxml.py", line 95, in processXml
    return response
UnboundLocalError: local variable 'response' referenced before assignment
2013-10-20 01:10:28,309 - ERROR: 500 POST /yixinpublic?timestamp=1382231421&nonce=8187933050564107&signature=d74ff5c052de356fca7ed872eb64d69dcacbe5a4 (223.252.198.65) 1.57ms
2013-10-20 03:12:52,059 - WARNING: 404 GET /robots.txt (66.249.75.233) 0.56ms
2013-10-20 03:12:53,071 - WARNING: 404 GET /vincentpc.github.com (66.249.64.1) 0.56ms
2013-10-20 04:48:46,349 - WARNING: 404 GET http://www.baidu.com/ (113.247.234.117) 0.60ms
2013-10-20 05:44:32,643 - WARNING: 405 HEAD / (54.208.21.190) 0.58ms
2013-10-20 07:42:05,704 - ERROR: Uncaught exception POST /yixinpublic?timestamp=1382254917&nonce=8211429834643069&signature=d91be889cebc3063784d4f2fe539fabf119dcc51 (223.252.198.65)
HTTPRequest(protocol='http', host='54.200.177.39', method='POST', uri='/yixinpublic?timestamp=1382254917&nonce=8211429834643069&signature=d91be889cebc3063784d4f2fe539fabf119dcc51', version='HTTP/1.1', remote_ip='223.252.198.65', headers={'Content-Length': '302', 'Host': '54.200.177.39', 'Content-Encoding': 'UTF-8', 'Content-Type': 'text/xml; charset=UTF-8', 'Connection': 'Keep-Alive', 'Accept': 'application/xml', 'User-Agent': 'Netease/0.1'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1141, in _when_complete
    callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1162, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "app.py", line 27, in post
    data = processXml(self.request.body)
  File "/home/ubuntu/tornado/wechatwiki/handlers/processxml.py", line 95, in processXml
    return response
UnboundLocalError: local variable 'response' referenced before assignment
2013-10-20 07:42:05,712 - ERROR: 500 POST /yixinpublic?timestamp=1382254917&nonce=8211429834643069&signature=d91be889cebc3063784d4f2fe539fabf119dcc51 (223.252.198.65) 8.98ms
2013-10-20 07:42:21,884 - ERROR: Uncaught exception POST /yixinpublic?timestamp=1382254934&nonce=8211446002555099&signature=522ee9b8e8cf1b5d4e442669b26b8730c809ee32 (223.252.198.65)
HTTPRequest(protocol='http', host='54.200.177.39', method='POST', uri='/yixinpublic?timestamp=1382254934&nonce=8211446002555099&signature=522ee9b8e8cf1b5d4e442669b26b8730c809ee32', version='HTTP/1.1', remote_ip='223.252.198.65', headers={'Content-Length': '300', 'Host': '54.200.177.39', 'Content-Encoding': 'UTF-8', 'Content-Type': 'text/xml; charset=UTF-8', 'Connection': 'Keep-Alive', 'Accept': 'application/xml', 'User-Agent': 'Netease/0.1'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1141, in _when_complete
    callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1162, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "app.py", line 27, in post
    data = processXml(self.request.body)
  File "/home/ubuntu/tornado/wechatwiki/handlers/processxml.py", line 95, in processXml
    return response
UnboundLocalError: local variable 'response' referenced before assignment
2013-10-20 07:42:21,885 - ERROR: 500 POST /yixinpublic?timestamp=1382254934&nonce=8211446002555099&signature=522ee9b8e8cf1b5d4e442669b26b8730c809ee32 (223.252.198.65) 1.60ms
2013-10-20 07:46:43,315 - ERROR: Uncaught exception POST /yixinpublic?timestamp=1382255195&nonce=8211707432047645&signature=6748bb394484974516861393cda68faf198e429e (223.252.198.65)
HTTPRequest(protocol='http', host='54.200.177.39', method='POST', uri='/yixinpublic?timestamp=1382255195&nonce=8211707432047645&signature=6748bb394484974516861393cda68faf198e429e', version='HTTP/1.1', remote_ip='223.252.198.65', headers={'Content-Length': '302', 'Host': '54.200.177.39', 'Content-Encoding': 'UTF-8', 'Content-Type': 'text/xml; charset=UTF-8', 'Connection': 'Keep-Alive', 'Accept': 'application/xml', 'User-Agent': 'Netease/0.1'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1141, in _when_complete
    callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1162, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "app.py", line 27, in post
    data = processXml(self.request.body)
  File "/home/ubuntu/tornado/wechatwiki/handlers/processxml.py", line 95, in processXml
    return response
UnboundLocalError: local variable 'response' referenced before assignment
2013-10-20 07:46:43,316 - ERROR: 500 POST /yixinpublic?timestamp=1382255195&nonce=8211707432047645&signature=6748bb394484974516861393cda68faf198e429e (223.252.198.65) 1.56ms
2013-10-20 07:47:09,422 - ERROR: Uncaught exception POST /yixinpublic?timestamp=1382255221&nonce=8211733505016470&signature=54f97a31868831f03ac8a06f72765cbebb948ae7 (223.252.198.65)
HTTPRequest(protocol='http', host='54.200.177.39', method='POST', uri='/yixinpublic?timestamp=1382255221&nonce=8211733505016470&signature=54f97a31868831f03ac8a06f72765cbebb948ae7', version='HTTP/1.1', remote_ip='223.252.198.65', headers={'Content-Length': '300', 'Host': '54.200.177.39', 'Content-Encoding': 'UTF-8', 'Content-Type': 'text/xml; charset=UTF-8', 'Connection': 'Keep-Alive', 'Accept': 'application/xml', 'User-Agent': 'Netease/0.1'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1141, in _when_complete
    callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1162, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "app.py", line 27, in post
    data = processXml(self.request.body)
  File "/home/ubuntu/tornado/wechatwiki/handlers/processxml.py", line 95, in processXml
    return response
UnboundLocalError: local variable 'response' referenced before assignment
2013-10-20 07:47:09,423 - ERROR: 500 POST /yixinpublic?timestamp=1382255221&nonce=8211733505016470&signature=54f97a31868831f03ac8a06f72765cbebb948ae7 (223.252.198.65) 1.59ms
